FROM node:22-alpine

WORKDIR /app

# Installer les dépendances
COPY package.json ./
COPY prisma ./prisma
# npm install créera package-lock.json automatiquement s'il n'existe pas
RUN npm install

# Générer le client Prisma
RUN npx prisma generate

EXPOSE 3000
ENV PORT=3000
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
